# Generated by Django 5.0 on 2023-12-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='vote',
            field=models.BooleanField(default=True),
        ),
    ]
