# Generated by Django 5.0 on 2024-01-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chat_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='issue_type',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
